
export const AUTH_CHECK = 'AUTH_CHECK';
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_BRIDEGROOM = 'GET_BRIDEGROOM';
export const DELETE_SUPPLIER = 'DELETE_USER';
export const DELETE_BRIDE = 'DELETE_BRIDE';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const EDIT_LOCATIONS = 'EDIT_LOCATIONS';
export const REMOVE_LOCATIONS = 'REMOVE_LOCATIONS';

export const ADD_LOCATIONS = 'ADD_LOCATIONS';

export const INIT_SUPPLIERS_TYPE = 'INIT_SUPPLIERS_TYPE';
export const DELETE_SUPPLIERS_TYPE = 'DELETE_SUPPLIERS_TYPE';
export const ADD_SUPPLIERS_TYPE = 'ADD_SUPPLIERS_TYPE';
export const EDIT_SUPPLIERS_TYPE = 'EDIT_SUPPLIERS_TYPE';










